### ISSUE TITLE
configuration failed ? 

### ISSUE THREAD

**Issue by T1loc** [javierllorente/qactus#2]
Refreshing view...
User-Agent: "Qactus 0.7.0"
Reply row property: "0"
URL: QUrl("http://api.opensuse.org/request?view=collection&states=new&roles=maintainer&user=T1loc")
HTTP status code: 404
OBSXmlReader addData()

I'm not able to get package or request list.

openSUSE_Leap x86_64, plasma5 

If you want more information, tell me.

Regards.

**Comment by javierllorente** [comment]
I see that you are using http instead of https. Does it work with https?

**Comment by T1loc** [comment]
- Edit -
  With https://api.opensuse.org/ it works.

With my own obs, this message is displayed : 
Api has been changed!
Proxy has been disabled
User-Agent: "Qactus 0.7.0"
Window activated
SSL Errors: "No certificates could be verified"
onSslErrors() url: QUrl("https://obs.xxxxxxxxx/") row: 0
Reply row property: "0"
URL: QUrl("https://obs.xxxxxxxxx/")
HTTP status code: 0
Request failed! Error: "SSL handshake failed"

Perhaps because anonymous access is disable?

**Comment by javierllorente** [comment]
It seems there is a server misconfiguration. For more details, please take a look at the output from
`openssl s_client -showcerts -connect obs.adthink-media.com:443`

**Comment by T1loc** [comment]
My bad, I close the issue.

Thank you.

**Comment by javierllorente** [comment]
It's ok :)
