### ISSUE TITLE
'Protocol "" is unknown' during login

### ISSUE THREAD

**Issue by z3ntu** [javierllorente/qactus#4]
![image](https://user-images.githubusercontent.com/3768500/49105354-a56e3900-f280-11e8-9042-9a810e1d221c.png)
Console log:
```
ainWindow::setupBrowser()
MainWindow::readSettings()
MainWindow::readProxySettings()
MainWindow::readAuthSettings()
MainWindow::readSettingsTimer() Timer Active = false
Window activated
MainWindow::setNotify() false
MainWindow::showLoginDialog()
Login::readSettings()
Credentials::readPassword()
Password restored successfully
Login::slotCredentialsRestored()
Login::readSettings() AutoLogin: false
Login::writeSettings()
Credentials::writeCredentials()
Credentials stored successfully
MainWindow::slotLogin()
OBSCore::setCredentials()
OBSCore::createManager()
User-Agent: "Qactus 1.0.0"
MainWindow::slotUpdateStatusBar()
Closing Login
OBSCore::replyFinished() "/"
OBSCore::replyFinished() HTTP status code: 0
OBSCore::replyFinished() Request failed! Error: "Protocol \"\" is unknown"
MainWindow::showNetworkError()
MainWindow::slotUpdateStatusBar()
```

I just opened the application (without having it opened before), selected login in the menu bar, entered my credentials and pressed Login

**Comment by javierllorente** [comment]
Could you please tell me the API URL you are using?

**Comment by z3ntu** [comment]
In the settings under `OBS API` `https://api.opensuse.org/` is listed

**Comment by javierllorente** [comment]
OK, thanks. Could you tell me your OS and Qt version?

**Comment by z3ntu** [comment]
Arch Linux latest, Qt 5.11.2.
Qactus version 1.0.0

**Comment by javierllorente** [comment]
`OBSCore::replyFinished() "/"` should be `OBSCore::replyFinished() "https://api.opensuse.org/"`
Sounds like `ApiUrl` is empty in `~/.config/Qactus/Qactus.conf`

**Comment by javierllorente** [comment]
`ApiUrl` was empty and kept empty unless you opened the "Configure Qactus" dialog and clicked on "OK". This will be fixed on next release. Thanks for your bug report!
