### ISSUE TITLE
Qactus should build itself on Suse OBS

### ISSUE THREAD

**Issue by zeroheure** [javierllorente/qactus#6]
Eat your own dog food :-)
Building Qactus on OBS could help users : documentatio non real example, working example, other distro packages, etc.

**Comment by javierllorente** [comment]
Great explanation, etc ;-)
It is already built on OBS. Please check https://build.opensuse.org/package/show/openSUSE:Factory/qactus

**Comment by zeroheure** [comment]
Very sorry, I've checked before reporting and didn't find it.
